version: '3.9'
volumes: 
    dados:
services: 
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes: 
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.19
    volumes: 
      # Site
      - ./frontend:/usr/share/nginx/html/
    ports: 
      - 80:80