version: '3.9'
volumes: 
    dados:
services: 
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes: 
      # Volume dos dados
      - dados:/var/lib/postgresql/data
