version: '3.9'
services: 
  app:
    environment: 
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=email_sender
      - REDIS_HOST=queue
  worker:
    environment: 
      - REDIS_HOST=queue